import ClientOnlyLayout from "@/components/ClientOnlyLayout";
import esteadadFont from "@/theme/localFonts";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${esteadadFont.variable}`}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ClientOnlyLayout>{children}</ClientOnlyLayout>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
