import esteadadFont from "@/theme/localFonts";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "./globals.css";
import ClientOnlyLayout from "@/components/ClientOnlyLayout";
import DrawerAppBar from "@/components/appbare/Appbare";
import { Toolbar } from "@mui/material";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        <ClientOnlyLayout>
          <body className={`${esteadadFont.variable}`}>
            <DrawerAppBar />
            <Toolbar />

            {children} 
            
            </body>
        </ClientOnlyLayout>
      </AppRouterCacheProvider>
    </html>
  );
}
